/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pr2_7;
import java.util.ArrayList;

/**
 *
 * @author Eli Gavett
 */
public class PR2_7 extends javax.swing.JFrame {
    ArrayList<CookieJar> cook = new ArrayList<>();
    /**
     * Creates new form PR2_7
     */
    public PR2_7() {
        initComponents();
        for(int a = 0; a < 3; a++)
            cook.add(new CookieJar());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblTitle = new javax.swing.JLabel();
        jLblTMName = new javax.swing.JLabel();
        jLblSamName = new javax.swing.JLabel();
        jLblCCName = new javax.swing.JLabel();
        jTFTMInput = new javax.swing.JTextField();
        jTFSamInput = new javax.swing.JTextField();
        jTFCCInput = new javax.swing.JTextField();
        jLblTMSold = new javax.swing.JLabel();
        jLblSamSold = new javax.swing.JLabel();
        jLblCCSold = new javax.swing.JLabel();
        jBtnSale = new javax.swing.JButton();
        jLblTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLblTitle.setText("Girl Scout Cookie Tracker");

        jLblTMName.setText("Thin Mints ($3) -");

        jLblSamName.setText("Samoas ($4) -");

        jLblCCName.setText("Chocolate Chip ($5)  - ");

        jTFSamInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFSamInputActionPerformed(evt);
            }
        });

        jLblTMSold.setText("0 Sold");

        jLblSamSold.setText("0 Sold");

        jLblCCSold.setText("0 Sold");

        jBtnSale.setText("Sold!");
        jBtnSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSaleActionPerformed(evt);
            }
        });

        jLblTotal.setText("Total Sales: $0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLblTMName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLblSamName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLblCCName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTFSamInput, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFTMInput, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jTFCCInput, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblTitle)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jBtnSale)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblTotal)
                    .addComponent(jLblTMSold)
                    .addComponent(jLblSamSold)
                    .addComponent(jLblCCSold))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLblTitle)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblTMName)
                    .addComponent(jTFTMInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblTMSold))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblSamName)
                    .addComponent(jTFSamInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblSamSold))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblCCName)
                    .addComponent(jTFCCInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblCCSold))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnSale)
                    .addComponent(jLblTotal)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFSamInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFSamInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFSamInputActionPerformed

    private void jBtnSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSaleActionPerformed
        int tm = Integer.parseInt(jTFTMInput.getText());
        int sam = Integer.parseInt(jTFSamInput.getText());
        int cc = Integer.parseInt(jTFCCInput.getText());
        
        cook.get(0).addCookies(3, tm);
        cook.get(1).addCookies(4, sam);
        cook.get(2).addCookies(5, cc);
        
        jLblTMSold.setText(cook.get(0).getCount() + " Sold");
        jLblSamSold.setText(cook.get(1).getCount() + " Sold");
        jLblCCSold.setText(cook.get(2).getCount() + " Sold");
        
        int tmTotal = cook.get(0).getValue();
        int samTotal = cook.get(1).getValue();
        int ccTotal = cook.get(2).getValue();
        
        jLblTotal.setText("Total Sales: $" + (tmTotal + samTotal + ccTotal));
    }//GEN-LAST:event_jBtnSaleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PR2_7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PR2_7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PR2_7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PR2_7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PR2_7().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnSale;
    private javax.swing.JLabel jLblCCName;
    private javax.swing.JLabel jLblCCSold;
    private javax.swing.JLabel jLblSamName;
    private javax.swing.JLabel jLblSamSold;
    private javax.swing.JLabel jLblTMName;
    private javax.swing.JLabel jLblTMSold;
    private javax.swing.JLabel jLblTitle;
    private javax.swing.JLabel jLblTotal;
    private javax.swing.JTextField jTFCCInput;
    private javax.swing.JTextField jTFSamInput;
    private javax.swing.JTextField jTFTMInput;
    // End of variables declaration//GEN-END:variables
}
