/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exam_1;
import java.io.*;
import java.util.ArrayList;

/**
 *
 * @author Eli Gavett
 */
public class Exam_1 extends javax.swing.JFrame {
    static Dice dice = new Dice(); //the dice used to roll
    static ArrayList<Player> players = new ArrayList<>(); //list of all recorded players
    static Player thePlayer; //the player currently using the program
    
    /**
     * Creates new form Exam_1
     */
    public Exam_1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblTitle = new javax.swing.JLabel();
        jLblLog = new javax.swing.JLabel();
        jTFLog = new javax.swing.JTextField();
        jBtnLog = new javax.swing.JButton();
        jLblCash = new javax.swing.JLabel();
        jLblName = new javax.swing.JLabel();
        jLblBet = new javax.swing.JLabel();
        jTFBet = new javax.swing.JTextField();
        jCBoxBet = new javax.swing.JComboBox();
        jBtnRoll = new javax.swing.JButton();
        jBtnSave = new javax.swing.JButton();
        jLblRoll = new javax.swing.JLabel();
        jLblResult = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLblTitle.setText("Under Over");

        jLblLog.setText("Name:");

        jBtnLog.setText("Log In!");
        jBtnLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLogActionPerformed(evt);
            }
        });

        jLblCash.setText("Holdings: $---");

        jLblName.setText("UserName: ---");

        jLblBet.setText("Your Bet: $");

        jTFBet.setText("0");

        jCBoxBet.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Under 7 1-1)", "7 (1-1)", "Over 7 (1-1)" }));

        jBtnRoll.setText("Roll!");
        jBtnRoll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRollActionPerformed(evt);
            }
        });

        jBtnSave.setText("Save");
        jBtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSaveActionPerformed(evt);
            }
        });

        jLblRoll.setText("Roll: --");

        jLblResult.setText("------------");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLblLog)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFLog, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBtnLog)
                    .addComponent(jLblTitle)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtnSave)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jCBoxBet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLblBet)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTFBet, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jBtnRoll))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblCash)
                    .addComponent(jLblName)
                    .addComponent(jLblRoll)
                    .addComponent(jLblResult))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLblTitle)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblLog)
                    .addComponent(jTFLog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnLog)
                    .addComponent(jLblCash))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblBet)
                    .addComponent(jTFBet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblRoll))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBoxBet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblResult))
                .addGap(18, 18, 18)
                .addComponent(jBtnRoll)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnSave)
                .addGap(0, 17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    /*
    * Calls the save method and saves player data
    * Notifys the user once the process has been complete
    */
    private void jBtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSaveActionPerformed
        save("C:\\Users\\Eli Gavett\\Documents\\GitHub\\CS372\\Exam_1\\Players.txt");
        System.out.println("User Data has been saved.");
    }//GEN-LAST:event_jBtnSaveActionPerformed
   
    /*
    * Takes the player name and tries to find thier data
    * If the player does not existed, a new player object is created and added to the arraylist
    * Updates the jLabels with the player data
    */
    private void jBtnLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLogActionPerformed
        try{
            String name = jTFLog.getText();
            if(name.contains(" "))
                throw new Exception("Names cannnot have a space in them");
            else if(name.equals(""))
                throw new Exception("A name should actually have characters, you know....");
            else{
                Boolean found = false;
                for(int a = 0; a < players.size(); ++a){
                    if(players.get(a).getName().equals(name)){
                        thePlayer = players.get(a);
                        found = true;
                    }
                }
                if(!found){
                    thePlayer = new Player(name);
                    players.add(thePlayer);
                }
                jLblName.setText("Username: " + thePlayer.getName());
                jLblCash.setText("Holdings: $" + thePlayer.getCash());
                    
            }
        }
        catch(Exception ex){
            System.out.println("Names should have at least 1 character. Names CANNOT have spaces in them.");
        }
    }//GEN-LAST:event_jBtnLogActionPerformed
    
    /*
    * If the players bet is valid, rolls the dice
    * Funds are removed or added to the players account based on their performance
    */
    private void jBtnRollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRollActionPerformed
        try{
            if(jTFBet.getText().equals(""))
                throw new Exception("Please enter an actual number");
            else{
                int betAmt = Integer.parseInt(jTFBet.getText());
                if(betAmt <= 0)
                    throw new Exception ("Bets should be $1 or greater.");
                betAmt = thePlayer.bet(betAmt);
                int betType = jCBoxBet.getSelectedIndex();
                int roll = dice.roll();
                jLblRoll.setText("Roll: " + roll);
                if(betType == dice.betType(roll)){
                    if(betType == 0 || betType == 2)
                        betAmt += betAmt;
                    else
                        betAmt *= 4;
                    jLblResult.setText("Success! You recieved $" + betAmt);
                    thePlayer.winnings(betAmt);
                }
                else
                    jLblResult.setText("Failure! You lost $" + betAmt);
                jLblCash.setText("Holdings: $" + thePlayer.getCash());
            }
        }
        catch(Exception ex){
            System.out.printf("You goofed. Again. \n", ex.getMessage());
        }
    }//GEN-LAST:event_jBtnRollActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exam_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exam_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exam_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exam_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        readFile("C:\\Users\\Eli Gavett\\Documents\\GitHub\\CS372\\Exam_1\\Players.txt");
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exam_1().setVisible(true);
            }
        });
    }
    
    /*
    * Reads Player Data from txt file location and saves it to players
    * @param file the file path
    */
    public static void readFile(String f){
        try{
            File file = new File(f);
            BufferedReader rdr = new BufferedReader(new FileReader(file));
            String line;
            int index2;
            while((line = rdr.readLine()) != null){
                index2 = line.indexOf(" ");
                String n = line.substring(0, index2);
                int c = Integer.parseInt(line.substring(index2 + 1));
                players.add(new Player(n, c));
            }
            rdr.close();
        }
        catch(Exception ex){
            System.out.printf("Well.... Bother. %s\n", ex.getMessage());
        }
    }
    
    /*
    * Saves player data to a txt file
    * @param file the file path
    */
    public static void save(String f){
        try{
            File file = new File(f);
            BufferedWriter wrtr = new BufferedWriter(new FileWriter(file));
            String line;
            for(int a = 0; a < players.size(); a++){
                line = players.get(a).toString();
                wrtr.write(line);
                wrtr.newLine();
            }
            wrtr.close();
        }
        catch(Exception ex){
            System.out.printf("Well.... Bother. %s\n", ex.getMessage());
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnLog;
    private javax.swing.JButton jBtnRoll;
    private javax.swing.JButton jBtnSave;
    private javax.swing.JComboBox jCBoxBet;
    private javax.swing.JLabel jLblBet;
    private javax.swing.JLabel jLblCash;
    private javax.swing.JLabel jLblLog;
    private javax.swing.JLabel jLblName;
    private javax.swing.JLabel jLblResult;
    private javax.swing.JLabel jLblRoll;
    private javax.swing.JLabel jLblTitle;
    private javax.swing.JTextField jTFBet;
    private javax.swing.JTextField jTFLog;
    // End of variables declaration//GEN-END:variables
}
